development:
  adapter: <%= ENV['DEV_DATABASE_ADAPTER'] %>
  encoding: <%= ENV['DEV_DATABASE_ENCODING'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV['DEV_DATABASE_TIMEOUT'] %>
  database: <%= ENV['DEV_DATABASE'] %>
  username: <%= ENV['DEV_DATABASE_USER'] %>

test:
  adapter: <%= ENV['DEV_DATABASE_ADAPTER'] %>
  encoding: <%= ENV['DEV_DATABASE_ENCODING'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV['DEV_DATABASE_TIMEOUT'] %>
  database: <%= ENV['DEV_DATABASE_TEST'] %>
  username: <%= ENV['DEV_DATABASE_USER'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_URL'] %>
